version: 2.1

jobs:
  test:
    filters:
      branches:
        only:
          - prod
          - uat
    docker:
      - image: python:latest
    steps:
      - run: echo "testing..."

  deploy:
    filters:
      branches:
        only:
          - prod
          - uat
    docker:
      - image: python:latest
    steps:
      - run: echo "deploying..."

workflows:
  build_deploy:
    jobs:
      - test
      - deploy
