version: 2.1

jobs:
  test:
    docker:
      - image: python:latest
    steps:
      - run: echo "testing..."

  deploy:
    docker:
      - image: python:latest
    steps:
      - run: echo "deploying...."

workflows:
  test_build:
    jobs:
      - test
      - deploy
